# config_dict 에 들어가는 기본 값들을 여기에 넣어주면 됨. 
# model configuration
model: SASRec

epochs : 100
stopping_step: 10
batch_size: 2048

# data_path: ./datasets/
data_path: /content/
dataset: movies_modified2

# dataset configuration
load_col:
  inter: [user_id, item_id,rating, timestamp]

valid_metric: Recall@10
NEG_PREFIX: neg_
loss_type: BPR